# Generated by Django 2.2.10 on 2020-05-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
    ]
